# INSTALL LIBRARIES ####
install.packages("devtools", dependencies = TRUE)
install.packages("tidyverse", dependencies = TRUE)
install.packages("arsenal", dependencies=TRUE)
install.packages("asbio", dependencies=TRUE)
install.packages("doBy", dependencies=TRUE)
install.packages("coin", dependencies = TRUE)
install.packages("data.table", dependencies=TRUE)
install.packages("dplyr", dependencies = TRUE)
install.packages("effsize", dependencies = TRUE)
install.packages("epiDisplay", dependencies=TRUE)
install.packages("furniture", dependencies=TRUE)
install.packages("ggmosaic", dependencies = TRUE)
install.packages("ggplot2", dependencies = TRUE)
install.packages("ggthemes", dependencies = TRUE)
install.packages("grid", dependencies = TRUE)
install.packages("gridExtra", dependencies = TRUE)
install.packages("gt", dependencies = TRUE)
install.packages("gtsummary", dependencies = TRUE)
install.packages("haven", dependencies = TRUE)
install.packages("IncidencePrevalence", dependencies = TRUE)
install.packages("iNEXT", dependencies=TRUE)
install.packages("Hmisc", dependencies = TRUE)
install.packages("lattice", dependencies=TRUE)
install.packages("lubridate", dependencies = TRUE)
install.packages("modeest", dependencies=TRUE)
install.packages("nortest", dependencies=TRUE)
install.packages("onewaytests", dependencies=TRUE)
install.packages("openxlsx", dependencies = TRUE)
install.packages("pastecs", dependencies=TRUE)
install.packages("pivottabler", dependencies=TRUE)
install.packages("psych", dependencies=TRUE)
install.packages("purrr", dependencies=TRUE)
install.packages("RcmdrMisc", dependencies = TRUE)
install.packages("RcmdrMisc", dependencies = TRUE)
install.packages("reticulate", dependencies=TRUE)
install.packages("RVAideMemoire", dependencies=TRUE)
install.packages("rvest", dependencies = TRUE)
install.packages("scales", dependencies = TRUE)
install.packages("summarytools", dependencies = TRUE)
install.packages("sur", dependencies = TRUE)
install.packages("swirl", dependencies = TRUE)
install.packages("s20x", dependencies=TRUE)
install.packages("tables", dependencies=TRUE)
install.packages("UsingR", dependencies=TRUE)
install.packages("waffle", dependencies=TRUE)

# OPEN ALL LIBRARIES ####
library(arsenal)
library(asbio)
library(coin)
library(devtools)
library(doBy)
library(dplyr)
library(dslabs)
library(effsize)
library(furniture)
library(grid)
library(gridExtra)
library(epiDisplay)
library(ggmosaic)
library(ggplot2)
library(ggthemes)
library(gt)
library(gtsummary)
library(Hmisc)
library(IncidencePrevalence)
library(iNEXT)
library(lattice)
library(lubridate)
library(modeest)
library(nortest)
library(onewaytests)
library(openxlsx)
library(pastecs)
library(pivottabler)
library(psych)
library(purrr)
library(RcmdrMisc)
library(RVAideMemoire)
library(rvest)
library(reticulate)
library(s20x)
library(scales)
library(summarytools)
library(sur)
library(swirl)
library(tables)
library(tidyverse)
library(UsingR)
library(waffle)

# OPEN LIBRARIES ####
library(lubridate)
library(tidyverse)

